name: Updates ics calendar

on:
  #push:
  workflow_dispatch:
  schedule:
    - cron:  '5 0 * * 5'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Install system dependencies
      run: |-
        apt-get update && apt-get -y install git libxml2-dev
    - name: Check out this repo
      uses: actions/checkout@v7
    - name: Install xml2
      run: |-
        . /etc/os-release
        Rscript -e "install.packages('xml2', repos='https://packagemanager.posit.co/cran/__linux__/${VERSION_CODENAME}/latest')"
    - name: Download and treat
      run: |-
        Rscript ecb.R
    - name: Commit and push if it changed
      run: |-
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git config user.name "Automatic"
        git config user.email "actions@users.noreply.github.com"
        git add docs/
        timestamp=$(date -u)
        git commit -m "Automatic update of ics calendar: ${timestamp}" || exit 0
        git push

    container: rocker/r-ver:latest
